### ISSUE TITLE
Javascript web page not rendering in splash

### ISSUE THREAD

**Issue by bgt-prabhakard** [scrapinghub/splash#194] opened 2015-03-16 12:12 UTC
I am using scrapy script to load URL using "yield".

MyUrl = "www.example.com"
request = Request(MyUrl, callback=self.mydetail)
yield request
def jobdetail(self, response):
item['Description'] = response.xpath(".//table[@class='list']//text()").extract()
return item

The URL seems to take minimum 5 seconds to load in browser because of javascript. So I want Scrapy to render javascript. I tried splash with scrapy but getting output as empty. I tried DOWNLOAD_DELAY also but not working.

**Comment by kmike** [comment] 2015-03-16 22:02
Hi @bgt-prabhakard,

Sorry, I don't quite understand your issue. The code you've pasted doesn't seem to use Splash. Could you please provide more details?

**Comment by bgt-prabhakard** [comment] 2015-03-18 05:19
Below is my settings.py

##############
BOT_NAME = 'ora'
SPIDER_MODULES = ['ora.spiders']
NEWSPIDER_MODULE = 'ora.spiders'
DOWNLOADER_MIDDLEWARES = { 'ora.middleware.splash.SplashMiddleware': 725 ,}
DOWNLOAD_DELAY = 5
CONCURRENT_REQUESTS = 500
CONCURRENT_ITEMS = 10
CONCURRENT_REQUESTS_PER_DOMAIN = 50
CONCURRENT_REQUESTS_PER_IP = 10
DEPTH_LIMIT = 0

**Comment by bgt-prabhakard** [comment] 2015-03-30 16:24
Hello @kmike 

Can you please give an example scrapy-splash script?

**Comment by kmike** [comment] 2015-03-30 16:26
Hi @bgt-prabhakard,

I haven't used scarpy-splash. Could you try https://github.com/scrapinghub/scrapyjs?

**Comment by kmike** [comment] 2015-04-12 17:45
I'm closing it because it seems the issue is not with Splash.

**Closed by kmike** 2015-04-12 17:45 UTC
