### ISSUE TITLE
splash:go timeouts on pages with unsupported content-type

### ISSUE THREAD

**Issue by lopuhin** [scrapinghub/splash#453] opened 2016-04-29 15:28 UTC
Given this script:

```
function main(splash)
  local url = splash.args.url
  return splash:go{url}
end
```

and this url: https://s3.amazonaws.com/kostia.lopuhin/114 the script times out after 30 seconds: this is an image served with an `application/octet-stream` content-type. Identical file with `image/jpeg` content-type (https://s3.amazonaws.com/kostia.lopuhin/115) works, and both files are less then 1k.

@kmike writes here https://github.com/TeamHG-Memex/undercrawler/issues/51#issuecomment-215746159:

> Splash doesn't handle unsupported content now (http://doc.qt.io/archives/qt-5.5/qwebpage.html#forwardUnsupportedContent-prop), to fix it we need to add an API for that in Splash

The use-case here is crawling using splash, where we do not know in advance what is the content-type, and use `splash:go` by default.

**Comment by kmike** [comment] 2016-11-30 16:57
I'm closing it as a duplicate of #91.

**Closed by kmike** 2016-11-30 16:57 UTC
