### ISSUE TITLE
Problem executing JS code

### ISSUE THREAD

**Issue by bertinatto** [scrapinghub/splash#77] opened 2014-03-06 15:59 UTC
Hi,

I'm facing some problems executing a JS on a specific website:
```
➜  ~  curl -X POST -H 'content-type: application/javascript' -d 'showModalDimmer(); dojo.publish("showResultsForPageNumber",[{pageNumber:"2",pageSize:"12", linkId:"WC_SearchBasedNavigationResults_pagination_link_right_categoryResults"}]);' 'http://localhost:8050/render.html?url=http://www.hhgregg.com/appliances-home/washers&timeout=60&wait=0.5'

<html><head>
<title>Invalid URL</title>
</head><body>
<h1>Invalid URL</h1>
The requested URL "/appliances-home/washers", is invalid.<p>
Reference #9.9b043bbb.1394120505.1585c2c6

</p></body></html>%
```
This JS code is executed when I click the "Next" button.

However, it works with a simpler JS code:
```
➜  ~  curl -X POST -H 'content-type: application/javascript' -d 'document.write("hello");' 'http://localhost:8050/render.html?url=http://www.hhgregg.com/appliances-home/washers&timeout=60&wait=0.5'

<html><head></head><body>hello</body></html>%
```
Also, splash doesn't seem to properly render the page when I visualize it using the browser.

Any thoughts?

**Comment by kmike** [comment] 2015-11-04 01:28
I can't reproduce it with Splash master: the original example returns a bunch of HTML now. Maybe the issue is fixed, or maybe the example became outdated. Either way, it is not clear what to do in Splash to fix this ticket, so I'm closing it.

**Closed by kmike** 2015-11-04 01:28 UTC
