### ISSUE TITLE
Proxy POST requests

### ISSUE THREAD

**Issue by munro** [scrapinghub/splash#302] opened 2015-09-10 18:43 UTC
POST requests do not seem to be going through the HTTP proxy.  They do appear in the `splash:on_request(callback)` and `splash:on_response_headers(callback)` hooks, but are not seen through the proxy.

Anyone has quick thoughts on where this issue may be in the code?

Related to #239 in that it deals with adding the ability to use `splash:http_get(...)` with POST requests, but I'm not sure if it's adding support for POST proxying as well.

**Comment by kmike** [comment] 2015-09-14 22:01
I'm not sure why isn't it working. Proxy is set using standard Qt API. Do you have an example to try at hand?

**Comment by pawelmhm** [comment] 2015-09-16 15:43
@munro POST requests from splash to target website are not supported yet they will be supported after merging related PR 239.

**Comment by kmike** [comment] 2015-09-16 15:45
@pawelmhm POST requests should already work fine if they are initiated by JS code.

**Comment by munro** [comment] 2015-09-16 22:57
If you fire some proxy server like `brew install mitmproxy && mitmproxy`, then run this script, you won't see any post requests coming through the proxy.  Also I tried using proxy profiles, which didn't work either. 😭

```python
import requests
from textwrap import dedent
import json

LUA_SOURCE = dedent('''
    function main(splash)
        splash:on_request(function(request)
            request:set_proxy{
                host = "localhost",
                port = 8080,
            }
        end)

        splash:go("https://dash.scrapinghub.com/")
        splash:wait(0.5)
        splash:runjs("document.querySelector('.sign-in-btn button').click()")

        local title = splash:evaljs("document.title")
        return {title=title}
    end
''').strip()

requests.post(
    url='http://localhost:8050/execute',
    data=json.dumps(dict(
        lua_source=LUA_SOURCE
    )),
    headers={
        'content-type': 'application/json',
    }
).content
```

**Comment by pawelmhm** [comment] 2015-09-17 07:42
hmm @munro this seems to work for me I run your script and I get results all right. Are you sure mitmproxy is configured ok? 

Note that you're proxying https url so I think mitmproxy will not see it if it's not configured correctly.

**Comment by Youwotma** [comment] 2015-09-21 15:55
I can reproduce this consistently with this lua script:
```
function main(splash)
    splash:on_request(function (request)
        request:set_proxy{'proxy_host', 8010, username='hunter2', password='hunter2'}
    end)

    assert(splash:go('http://httpbin.org/forms/post'))

    assert(splash:wait(1))
    splash:runjs([[
        document.querySelector('form').submit();   
    ]])
    splash:wait(3)
    return {
        html = splash:html(),
        har = splash:har(),
    }
end
```
In the resulting html there is a field with the requesting IP where you should see the proxy's IP not yours. Crawlera or any other proxy should be ok to test this.

**Comment by munro** [comment] 2015-09-22 19:24
thanks for validating!  any idea where this issue may be?  I fruitlessly tried writing a test & poking around a little bit.

**Comment by kmike** [comment] 2015-09-22 19:26
@Youwotma found out that if you remove [this](https://github.com/scrapinghub/splash/blob/8b18d01662a4231647f1e9236e446fe7d73bc19c/splash/network_manager.py#L167) line then it starts to work. I'm trying to debug it and find a workaround because this line is needed.

**Comment by kmike** [comment] 2015-09-22 22:39
Hey @munro and @Youwotma - I pushed a fix to master; could you please check if it fixes an issue for you?

**Comment by kmike** [comment] 2015-09-22 22:49
Ouch, tests are failing on Travis

**Comment by Youwotma** [comment] 2015-09-23 03:36
@kmike I'll check!

**Comment by kmike** [comment] 2015-09-25 22:38
Tests are fixed by https://github.com/scrapinghub/splash/pull/308.

@Youwotma does the fix work for you, is it OK to close this ticket?

**Comment by Youwotma** [comment] 2015-09-29 07:59
Sorry, missed your comment. Yes, it works for me, thank you!

**Closed by Youwotma** 2015-09-29 07:59 UTC
