### ISSUE TITLE
Lua while loop problem

### ISSUE THREAD

**Issue by WUJJU** [scrapinghub/splash#389] opened 2016-02-24 20:10 UTC
**I am trying run lua code in splash. But fail and don't know how to continue. 
Below is my code. Anyone know how to run while loop in splash?**

import scrapy
from scrapy.selector import Selector
from splashtry.items import SplashtryItem

class MySpider(scrapy.Spider):
    name="ssplash"
    allowed_domains=["twitter.com"]
    start_urls = ["https://twitter.com/ScrapingHub","https://twitter.com/Jackie_Sap"]
    
    

    def start_requests(self):
        for url in self.start_urls:
            script="""
            local Splash=require("splash")
            function Splash:wait_for(condition)
                  while not condition() do
                      assert(splash:runjs("window.scrollTo(0,document.body.scrollHeight)"))
                      assert(self:wait(0.5))
                  end
            end 
            require("wait_for")

            function main(splash)
                 assert(splash:go(splash.args.url)) 
                 splash:wait_for(function()
                    return splash:evaljs("document.body.scrollTop == document.body.scrollHeight")
                 end)
                
                 return splash:html()
            end
            """
                 
            yield scrapy.Request(url, self.parse, meta={
                'splash': {
                    'args':{'lua_source':script},
                    'endpoint':'execute',
                }
            })

    def parse(self, response):    
        sel=Selector(response)
        item=SplashtryItem()
        items=[]   
        item['tweets']=sel.xpath('//div[@class="js-tweet-text-container"]/p/text()').extract()
        item['location']=sel.xpath('//span[@class="ProfileHeaderCard-locationText u-dir"]').extract()
        item['birth']=sel.xpath('//span[@class="ProfileHeaderCard-birthdateText u-dir"]').extract()
        item['name'] = sel.xpath('//title/text()').extract() 
        items.append(item)
        return items

**Comment by kmike** [comment] 2016-02-24 20:58
I think the problem is with `local Splash=require("splash")` - this module is not available by default sandbox settings. You likely copied splasg:wait_for example from [Writing Modules]](http://splash.readthedocs.org/en/stable/scripting-libs.html#writing-modules) docs, but this section is specifically about writing modules which you set up at Splash startup time, not about writing scripts you're sending to Splash.

In future please post the error message you get from Splash, it should contain useful information.

**Comment by kmike** [comment] 2016-02-24 20:59
```lua
-- wait_for function without all these modules
function wait_for(splash, condition)
    while not condition() do
        splash:wait(0.05)
    end
end
```

**Comment by WUJJU** [comment] 2016-02-25 03:16
Hi @kmike , base on your function, I changed my code. But it run into another error, could you help me look at it?



```
 def start_requests(self):
        for url in self.start_urls:
            script="""
            function wait_for(splash, condition)
                 while not condition() do
                      assert(splash:runjs("window.scrollTo(0,document.body.scrollHeight)"))
                      splash:wait(0.5)
                 end
            end

```

            function main(splash)
                 assert(splash:go(splash.args.url)) 

                 wait_for(splash, function()
                        return splash:evaljs("document.body.scrollTop == document.body.scrollHeight")
                 end)
                
                 return splash:html()
            end
            """
                 
            yield scrapy.Request(url, self.parse, meta={
                'splash': {
                    'args':{'lua_source':script},
                    'endpoint':'execute',
                }
            })

**Now the error shows:**
2016-02-24 22:10:34 [scrapy] INFO: Scrapy 1.0.5 started (bot: splashtry)
2016-02-24 22:10:34 [scrapy] INFO: Optional features available: ssl, http11
2016-02-24 22:10:34 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'splashtry.spiders', 'FEED_URI': 'si.json', 'DUPEFILTER_CLASS': 'scrapyjs.SplashAwareDupeFilter', 'SPIDER_MODULES': ['splashtry.spiders'], 'BOT_NAME': 'splashtry', 'FEED_FORMAT': 'json', 'HTTPCACHE_STORAGE': 'scrapyjs.SplashAwareFSCacheStorage', 'DOWNLOAD_DELAY': 1}
2016-02-24 22:10:34 [scrapy] INFO: Enabled extensions: CloseSpider, FeedExporter, TelnetConsole, LogStats, CoreStats, SpiderState
2016-02-24 22:10:35 [py.warnings] WARNING: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapyjs/middleware.py:8: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  from scrapy import log

2016-02-24 22:10:35 [py.warnings] WARNING: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapyjs/dupefilter.py:8: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  from scrapy.dupefilter import RFPDupeFilter

2016-02-24 22:10:35 [py.warnings] WARNING: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapyjs/cache.py:11: ScrapyDeprecationWarning: Module `scrapy.contrib.httpcache` is deprecated, use `scrapy.extensions.httpcache` instead
  from scrapy.contrib.httpcache import FilesystemCacheStorage

2016-02-24 22:10:35 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, SplashMiddleware, ChunkedTransferMiddleware, DownloaderStats
2016-02-24 22:10:35 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2016-02-24 22:10:35 [scrapy] INFO: Enabled item pipelines: 
2016-02-24 22:10:35 [scrapy] INFO: Spider opened
2016-02-24 22:10:35 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-02-24 22:10:35 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-02-24 22:11:05 [scrapy] DEBUG: Retrying <POST http://192.168.99.100:8050/execute> (failed 1 times): 504 Gateway Time-out
2016-02-24 22:11:06 [scrapy] DEBUG: Retrying <POST http://192.168.99.100:8050/execute> (failed 1 times): 504 Gateway Time-out
2016-02-24 22:11:11 [scrapy] DEBUG: Retrying <POST http://192.168.99.100:8050/execute> (failed 2 times): 400 Bad Request
2016-02-24 22:11:11 [scrapy] DEBUG: Retrying <POST http://192.168.99.100:8050/execute> (failed 2 times): 400 Bad Request
2016-02-24 22:11:35 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-02-24 22:11:41 [scrapy] DEBUG: Gave up retrying <POST http://192.168.99.100:8050/execute> (failed 3 times): 504 Gateway Time-out
2016-02-24 22:11:41 [scrapy] DEBUG: Crawled (504) <POST http://192.168.99.100:8050/execute> (referer: None)
2016-02-24 22:11:41 [scrapy] DEBUG: Ignoring response <504 http://192.168.99.100:8050/execute>: HTTP status code is not handled or not allowed
2016-02-24 22:11:42 [scrapy] DEBUG: Gave up retrying <POST http://192.168.99.100:8050/execute> (failed 3 times): 504 Gateway Time-out
2016-02-24 22:11:42 [scrapy] DEBUG: Crawled (504) <POST http://192.168.99.100:8050/execute> (referer: None)
2016-02-24 22:11:42 [scrapy] DEBUG: Ignoring response <504 http://192.168.99.100:8050/execute>: HTTP status code is not handled or not allowed
2016-02-24 22:11:42 [scrapy] INFO: Closing spider (finished)
2016-02-24 22:11:42 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 5613,
 'downloader/request_count': 6,
 'downloader/request_method_count/POST': 6,
 'downloader/response_bytes': 1746,
 'downloader/response_count': 6,
 'downloader/response_status_count/400': 2,
 'downloader/response_status_count/504': 4,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 2, 25, 3, 11, 42, 649283),
 'log_count/DEBUG': 11,
 'log_count/INFO': 8,
 'log_count/WARNING': 3,
 'response_received_count': 2,
 'scheduler/dequeued': 8,
 'scheduler/dequeued/memory': 8,
 'scheduler/enqueued': 8,
 'scheduler/enqueued/memory': 8,
 'splash/execute/request_count': 2,
 'splash/execute/response_count/400': 2,
 'splash/execute/response_count/504': 4,
 'start_time': datetime.datetime(2016, 2, 25, 3, 10, 35, 145048)}

**Comment by kmike** [comment] 2016-03-03 17:16
hey @WUJJU,

The log shows 'bad request'; I suggest to debug your script first in Splash UI: visit `<your-splash-url>:8050` in a browser and put your script there.

**Comment by kmike** [comment] 2016-03-03 17:18
also note you've got 504 error, it means that request timeouts. Default timeout is 30s, and it looks like your script doesn't finish in this time. Maybe waiting condition never occured - try e.g. limiting a number of iterations in wait_for.

**Comment by kmike** [comment] 2016-03-16 19:51
I'm closing this issue because it doesn't look like a Splash bug.

**Closed by kmike** 2016-03-16 19:51 UTC

**Comment by WUJJU** [comment] 2016-03-16 19:53
Sorry, I forget to close it.
