### ISSUE TITLE
I want lua return not waiting for all resource loaded finish.

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#445] opened 2016-04-18 22:23 UTC
Hi, 

Dose splash could accomplish my problem?
Sometimes, I just care a element or a resource, not the whole page.
It is possible let lua return immediately when meet some conditions?

Any question is welcome :)

**Comment by kmike** [comment] 2016-04-19 13:02
Yeah, that's be anice feature. See also: https://github.com/scrapinghub/splash/issues/127.

**Comment by genius001** [comment] 2016-04-19 21:16
Yes, the purpose of #127 is same with me.
Look forward to it.

**Comment by kmike** [comment] 2016-04-20 03:36
@genius001 I'm closing it as a duplicate of #127 then. Your vote for this feature is accounted :)

**Closed by kmike** 2016-04-20 03:36 UTC
